# Generated by Django 5.2.4 on 2025-08-04 21:43

from django.db import migrations


def create_missing_profiles(apps, schema_editor):
    User = apps.get_model('auth', 'User')
    UserProfile = apps.get_model('users', 'UserProfile')
    
    # Create profiles for users that don't have them
    for user in User.objects.all():
        UserProfile.objects.get_or_create(user=user)


def reverse_create_missing_profiles(apps, schema_editor):
    # No need to reverse this operation
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_missing_profiles, reverse_create_missing_profiles),
    ]
