# Generated by Django 5.2.4 on 2025-08-06 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_create_missing_profiles'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
